targets:
  $default:
    builders:
      drift_dev:
        options:
          fatal_warnings: true
          generate_manager: false
          sql:
            dialect: sqlite
            options:
              version: "3.34"
              modules:
                - json1
                - fts5
